language: php
php:
  #- '5.4'
  - '5.5'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  #- composer install --prefer-source --no-interaction --dev
  - phpenv config-add config.travis

# Commands you want to run that will verify your build.
script: phpunit --configuration phpunit.xml --coverage-text
